- name: Install rbenv & Ruby
  become_user: "{{ app_user }}"
  shell: |
    if [ ! -d "$HOME/.rbenv" ]; then
      git clone https://github.com/rbenv/rbenv.git ~/.rbenv
    fi
    echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
    echo 'eval "$(rbenv init -)"' >> ~/.bashrc
    if [ ! -d "$HOME/.rbenv/plugins/ruby-build" ]; then
      git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
    fi
    export PATH="$HOME/.rbenv/bin:$PATH"
    eval "$(rbenv init -)"
    rbenv install -s {{ ruby_version }}
    rbenv global {{ ruby_version }}
  args:
    executable: /bin/bash
